name: Bug report
description: Report errors or unexpected behavior
labels:
- bug
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/mienaiyami/react-ts-offline-manga-reader/issues) before filing a new one!

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots.
    placeholder: Having detailed steps helps us reproduce the bug. 
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false
