name: ❓ Question
description: Ask question related to this app.
labels:
- question
body:
- type: textarea
  attributes:
    label: Question
    description: Question.
  validations:
    required: true